---
title : "Instructions préalables au tutoriel"
subtitle: Etre prêt pour le jour J
format: html
author: ""
date: last-modified
---

::: callout-tip

## Besoin d'aide avant le jour J ?

Christophe sera présent un peu en amont le jour J (avant 10h donc) si jamais vous avez des problèmes à partager en amont du tutoriel. 

Vous pouvez le contacter avant également: [@cderv](https://github.com/cderv). 

Il est aussi disponible sur [grrr](https://r-grrr.slack.com/) : communauté Slack francophone ouverte à tous, notamment aux débutants. Pour rejoindre les discussions, suivre [le lien d’invitation](https://join.slack.com/t/r-grrr/shared_invite/zt-46utbgb9-uvo_bg5cbuxOV~H10YUX8w)
:::

Avant le tutoriel, veuillez suivre les étapes suivantes :

## Avant de venir

{{< include _preparatif-config.qmd >}}

{{< include _preparatif-files.qmd >}}

::: {.callout-tip}

# Conseil

Créez un dossier dédié sur votre environment pour la tutoriel afin d'y stocker les exercices, vos notes et pouvoir faire les exercices dans un environnement sain.

**Ne pas créer de dossier RStudio car nous allons créer différents projets pour les exercices, et créer des sous-projets RStudio ne fonctionne pas bien**

Exemple d'organisation: 

```
> tuto-quarto-RR-2023
|-- notes/
|-- exercices/
  |-- projet-rstudio1/
  |-- projet-quarto1/
|-- README.md (pour y noter le contexte de ce dossier)
```
:::

## À connaître (ou réviser) pour être à l'aise

Hypothèse pour le tutoriel : Vous connaissez R Markdown et vous connaissez la syntax Markdown.

-   La syntaxe Markdown pour Pandoc
    -   C'est la même que R Markdown :   
        <https://bookdown.org/yihui/rmarkdown/markdown-syntax.html>

    -   Elle est rappelée aussi pour Quarto :  
        <https://quarto.org/docs/authoring/markdown-basics.html>

-   Inclure du code R avec **knitr**
    -   Les chunks de code R :  
        <https://bookdown.org/yihui/rmarkdown/r-code.html>

    -   C\'est quoi un fichier R Markdown en fait :  
        <https://bookdown.org/yihui/rmarkdown-cookbook/rmarkdown-anatomy.html>

## Vérifier son setup

Quelques astuces pour vérifier son installation si vous avez installez quarto vous même:

* `quarto check install` doit fonctionner sans erreur 
  ```powershell
  $ quarto check install

    [>] Checking Quarto installation......OK
        Version: 1.4.146
        Path: C:\Users\chris\scoop\apps\quarto-prerelease\current\bin
        CodePage: 1252

    [>] Checking basic markdown render....OK
   ```

* `quarto check knitr` doit fonctonner sans erreur 
  ```powershell
  $ quarto check knitr

    (-) Checking R installation...........

    [>] Checking R installation...........OK
        Version: 4.2.2
        Path: C:/PROGRA~1/R/R-42~1.2
        LibPaths:
            - C:/Users/chris/AppData/Local/R/win-library/4.2
            - C:/Program Files/R/R-4.2.2/library
        knitr: 1.43
        rmarkdown: 2.22

    [>] Checking Knitr engine render......OK
  ```